name: build-and-push-docker-image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GHCR 
      uses: docker/login-action@v1  
      with: 
        registry: ghcr.io 
        username: danielgospodinow 
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: "."
        push: true
        tags: ghcr.io/qbaware/qbaware-discord-bot:latest
